"""Add missing commodity columns

Revision ID: 7a354a7a6bc4
Revises: 367708e34977
Create Date: 2026-01-28 10:59:43.123399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a354a7a6bc4'
down_revision: Union[str, Sequence[str], None] = '367708e34977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_actions', sa.Column('target_user_id', sa.UUID(), nullable=True))
    op.add_column('admin_actions', sa.Column('target_resource_id', sa.UUID(), nullable=True))
    op.add_column('admin_actions', sa.Column('description', sa.Text(), nullable=True))
    # Skip JSONB to JSON conversion - JSONB is better for PostgreSQL
    op.create_foreign_key(None, 'admin_actions', 'users', ['target_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('commodities', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('commodities', sa.Column('unit', sa.String(length=20), nullable=True))
    op.alter_column('mandis', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('mandis', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('notifications', sa.Column('related_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('price_forecasts', sa.Column('mandi_id', sa.UUID(), nullable=True))
    # Copy data from forecasted_price to predicted_price before dropping
    op.add_column('price_forecasts', sa.Column('predicted_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute('UPDATE price_forecasts SET predicted_price = forecasted_price WHERE predicted_price IS NULL')
    op.alter_column('price_forecasts', 'predicted_price', nullable=False, server_default=sa.text('0'))
    op.add_column('price_forecasts', sa.Column('confidence_level', sa.Numeric(precision=5, scale=4), nullable=True))
    # Copy data from confidence_score to confidence_level before dropping
    op.execute('UPDATE price_forecasts SET confidence_level = confidence_score WHERE confidence_level IS NULL')
    op.add_column('price_forecasts', sa.Column('model_version', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'price_forecasts', 'mandis', ['mandi_id'], ['id'], ondelete='CASCADE')
    op.drop_column('price_forecasts', 'confidence_score')
    op.drop_column('price_forecasts', 'forecasted_price')
    op.add_column('price_history', sa.Column('mandi_id', sa.UUID(), nullable=True))
    # Copy data from price to modal_price before dropping
    op.add_column('price_history', sa.Column('modal_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute('UPDATE price_history SET modal_price = price WHERE modal_price IS NULL')
    op.alter_column('price_history', 'modal_price', nullable=False, server_default=sa.text('0'))
    op.add_column('price_history', sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('price_history', sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'price_history', 'mandis', ['mandi_id'], ['id'], ondelete='CASCADE')
    op.drop_column('price_history', 'price')
    op.drop_column('price_history', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('price_history', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.drop_column('price_history', 'max_price')
    op.drop_column('price_history', 'min_price')
    op.drop_column('price_history', 'modal_price')
    op.drop_column('price_history', 'mandi_id')
    op.add_column('price_forecasts', sa.Column('forecasted_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('price_forecasts', sa.Column('confidence_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'price_forecasts', type_='foreignkey')
    op.drop_column('price_forecasts', 'model_version')
    op.drop_column('price_forecasts', 'confidence_level')
    op.drop_column('price_forecasts', 'predicted_price')
    op.drop_column('price_forecasts', 'mandi_id')
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'related_id')
    op.alter_column('mandis', 'address',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('mandis', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('commodities', 'unit')
    op.drop_column('commodities', 'category')
    op.drop_constraint(None, 'admin_actions', type_='foreignkey')
    # Skip JSON to JSONB conversion - keeping JSONB
    op.drop_column('admin_actions', 'description')
    op.drop_column('admin_actions', 'target_resource_id')
    op.drop_column('admin_actions', 'target_user_id')
    # ### end Alembic commands ###
